### ISSUE TITLE
Controller does not get the expected Rx packets after increasing the packet qSize 

### ISSUE THREAD

**Issue by sharonshenzhen** [cisco-open/go-p4#8]
Hi, 

After increasing the packet qSize (issue was reported in https://github.com/cisco-open/go-p4/issues/5), the Rx packets reported is still less than the expected number of the packets. 

Here is the code snippet to set the qSize: 
client0Stream0 := leader.StreamChannelGet(&streamName)
	if client0Stream0 == nil {
		t.Logf("'%s' nil stream", streamName)
	}

	arbCntrs := client0Stream0.GetArbCounters()
	t.Logf("stream '%s' Arbitration Counters RxArbCntr(%d) RxArbCntrDrop(%d) RxArbCntrQueued(%d)",
		streamName, arbCntrs.RxArbCntr, arbCntrs.RxArbCntrDrop, arbCntrs.RxArbCntrQueued)

	qSize := 5000
	client0Stream0.SetArbQSize(qSize)
	qSizeRead := client0Stream0.GetArbQSize()
	if qSize != qSizeRead {
		t.Logf("Stream '%s' expecting Arbitration qSize(%d) Got (%d)",
			streamName, qSize, qSizeRead)
	}
	pktCntrs := client0Stream0.GetPacketCounters()
	t.Logf("stream '%s' Packet Counters RxPktCntr(%d) RxPktCntrDrop(%d) RxPktCntrQueued(%d)",
		streamName, pktCntrs.RxPktCntr, pktCntrs.RxPktCntrDrop, pktCntrs.RxPktCntrQueued)

	client0Stream0.SetPacketQSize(qSize)
	qSizeRead = client0Stream0.GetPacketQSize()
	t.Logf(" qSizeRead is %d", qSizeRead)

	if qSize != qSizeRead {
		t.Logf("Stream '%s' expecting Packet qSize(%d) Got (%d)",
			streamName, qSize, qSizeRead)
	}

After the ATE sent more than 1496 packets (GDP and LLDP packets), the packet received reported from the controller is around 331, and no drop packets reported. 

This is the snippet of the code to get the RxPktCtr .

// get the packet counters
	client0Stream0 := client.StreamChannelGet(&streamName)
	pktCntrs := client0Stream0.GetPacketCounters()
	t.Logf("stream '%s' Packet Counters RxPktCntr(%d) RxPktCntrDrop(%d) RxPktCntrQueued(%d)",
		streamName, pktCntrs.RxPktCntr, pktCntrs.RxPktCntrDrop, pktCntrs.RxPktCntrQueued)

Script run output is shown as below: 

// get the packet counters
	client0Stream0 := client.StreamChannelGet(&streamName)
	pktCntrs := client0Stream0.GetPacketCounters()
	t.Logf("stream '%s' Packet Counters RxPktCntr(%d) RxPktCntrDrop(%d) RxPktCntrQueued(%d)",
		streamName, pktCntrs.RxPktCntr, pktCntrs.RxPktCntrDrop, pktCntrs.RxPktCntrQueued)

=== RUN   TestPacketIn/PacketIn_to_Primary_Controller
    p4rt_61_test.go:317: packets len is 0
    p4rt_61_test.go:317: stream 'p4rt' Packet Counters RxPktCntr(329) RxPktCntrDrop(0) RxPktCntrQueued(329)
    p4rt_61_test.go:318:  packets len is 331.    <<<<<<<<<<<<<<<<
    p4rt_61_test.go:327: Start to decode packet and compare with expected packets.
=== CONT  TestPacketIn
    p4rt_61_test.go:390: gdpPacketNo is '221'.  <<<<<<<<<<<<<<
    p4rt_61_test.go:391: lldpPacketNo is '110'.   <<<<<<<<<<<<<<<
--- PASS: TestPacketIn (426.50s)
    --- PASS: TestPacketIn/PacketIn_to_Primary_Controller (0.01s)
PASS

*** Releasing the testbed...

*** PROPERTY: time.end -> 1671229848
*** PROPERTY: time.begin -> 1671229391

Thanks,

Sharon

**Comment by rsindhujha** [comment]
@rnhaddad , can you please take a look? the RxPktCntr is always showing less value inspite of increasing the queue size for packets?

**Comment by rnhaddad** [comment]
Sorry for the delay given the holidays and time off...
I will look into this ASAP.

**Comment by rnhaddad** [comment]
Looked into the code, and nothing obvious that can pinpoint the issue.
Looking at the snippet above, there is not enough info to troubleshoot the problem. Possible issues i can think of:
1. Are you closing the stream/connection during the test?
2. Are you changing mastership/Election-id during the test?
3. The snippet shows that the queue size is set AFTER collecting the counters. Shouldn't this be the other way around (note that the drop counters show zero, which indicates no drops, but the counters should be read continuously in poll mode; are you doing that?)?
4. Have you looked into the glog file for any indication of the Go routine exiting prematurely?
5. Are you sure the server is sending 1496 packets to the client? Perhaps there is drop on the server side such that packets never show up on the client side?

Happy to help troubleshoot, but there is not enough info to conclude here.

**Comment by rnhaddad** [comment]
Hi, any updates on this front?

**Comment by sharonshenzhen** [comment]
Hi @rnhaddad  Thank you for your reply. 

Please see my comments for the questions:

1. Are you closing the stream/connection during the test?
No 

2. Are you changing mastership/Election-id during the test?
No.

3. The snippet shows that the queue size is set AFTER collecting the counters. Shouldn't this be the other way around (note that the drop counters show zero, which indicates no drops, but the counters should be read continuously in poll mode; are you doing that?)?

>> The snippet just want to show if the way to set the qSize correct or not, it is not the whole pictures of the code. 

Here is the complete code for setting the qSize and read the packets: 

       ...... 
        lldpTrafficFlow := args.lldppacketIO.GetTrafficFlow(args.ate, lldpPacketSize, lldpBitRate)
        gdpTrafficFlow := args.gdppacketIO.GetTrafficFlow(args.ate, gdpPacketSize, gdpBitRate)

        var flows []*ondatra.Flow
        flows = append(flows, gdpTrafficFlow...)
        flows = append(flows, lldpTrafficFlow...)

        client0Stream0 := leader.StreamChannelGet(&streamName)
        if client0Stream0 == nil {
                t.Logf("'%s' nil stream", streamName)
        }

       // Check the init count 
        arbCntrs := client0Stream0.GetArbCounters()
        t.Logf("stream '%s' Arbitration Counters RxArbCntr(%d) RxArbCntrDrop(%d) RxArbCntrQueued(%d)",
                streamName, arbCntrs.RxArbCntr, arbCntrs.RxArbCntrDrop, arbCntrs.RxArbCntrQueued)
       
       // Change qSize 
        qSize := 3500
        client0Stream0.SetArbQSize(qSize)
        qSizeRead := client0Stream0.GetArbQSize()
        if qSize != qSizeRead {
                t.Logf("Stream '%s' expecting Arbitration qSize(%d) Got (%d)",
                        streamName, qSize, qSizeRead)
        }
        pktCntrs := client0Stream0.GetPacketCounters()
        t.Logf("stream '%s' Packet Counters RxPktCntr(%d) RxPktCntrDrop(%d) RxPktCntrQueued(%d)",
                streamName, pktCntrs.RxPktCntr, pktCntrs.RxPktCntrDrop, pktCntrs.RxPktCntrQueued)
       
       // read the qSize 
        client0Stream0.SetPacketQSize(qSize)
        qSizeRead = client0Stream0.GetPacketQSize()
        t.Logf(" qSizeRead is %d", qSizeRead)

        if qSize != qSizeRead {
                t.Logf("Stream '%s' expecting Packet qSize(%d) Got (%d)",
                        streamName, qSize, qSizeRead)
                                                        
      }

       // Sending traffic 
        testTraffic(t, args.ate, flows, srcEndPoint, 10)

         // Init the packetno for each protocol
        gdpPacketNo := 0
        lldpPacketNo := 0

        for _, test := range packetInTests {
                t.Run(test.desc, func(t *testing.T) {
                        // Extract packets from PacketIn message sent to p4rt client                  
                        packets := fetchPackets(ctx, t, test.client, 3500)
                        t.Logf(" packets len is %d", len(packets))
.......

In side fetchPackets Function: 

// fetchPackets reads p4rt packets sent to p4rt client.
func fetchPackets(ctx context.Context, t *testing.T, client *p4rt_client.P4RTClient, expectNumber int) []*p4rt_client.P4RTPacketInfo {
        t.Helper()

        packets := []*p4rt_client.P4RTPacketInfo{}
        t.Logf("packets len is %d", len(packets))

        // get the packet counters
        client0Stream0 := client.StreamChannelGet(&streamName)
        pktCntrs := client0Stream0.GetPacketCounters()
        t.Logf("stream '%s' Packet Counters RxPktCntr(%d) RxPktCntrDrop(%d) RxPktCntrQueued(%d)",
                streamName, pktCntrs.RxPktCntr, pktCntrs.RxPktCntrDrop, pktCntrs.RxPktCntrQueued). 

        for i := 0; i < expectNumber; i++ {
                _, packet, err := client.StreamChannelGetPacket(&streamName, 0)
                if err == io.EOF {
                        t.Logf("EOF error is seen in PacketIn.")
..............


The log printed  below out is from fetchPackets function, not from the code before setting the qSize. 
p4rt_61_test.go:317: packets len is 0
p4rt_61_test.go:317: stream 'p4rt' Packet Counters RxPktCntr(329) RxPktCntrDrop(0) RxPktCntrQueued(329)






4. Have you looked into the glog file for any indication of the Go routine exiting prematurely?
No 

5. Are you sure the server is sending 1496 packets to the client? Perhaps there is drop on the server side such that packets never show up on the client side?

I remember that we checked on the server, the stats showed sending 1496 packets to the client. 

Thanks,

Sharon

**Comment by rnhaddad** [comment]
@sharonshenzhen,

From this:
Packet Counters RxPktCntr(329) RxPktCntrDrop(0) RxPktCntrQueued(329)

We can infer that the total number of times the QueuePacket function and thus the "case *p4_v1.StreamMessageResponse_Packet:" was called is 329.
The code is simple enough here, there are no hidden 'drops', right?

So what happened to the remaining callbacks or packets?!? We can not seem to reproduce this issue, so i am wondering if the server is actually sending these packets and/or flushing the gRPC queue from the server side?

Unfortunately, i don't have enough info to figure this out based on the above, and it is not something that i can reproduce.  Is it reproducible for you? If yes, i can be available to help troubleshoot if that helps...

**Comment by sharonshenzhen** [comment]
@rnhaddad 

Thank you for your quick response. 

Yes, it is reproducible on my setup. 

Thanks,

Sharon

**Comment by rnhaddad** [comment]
How do you want to proceed? I can not seem to reproduce this problem locally (but we might be using different P4RT servers).

**Comment by rsindhujha** [comment]
hi @rnhaddad , just for confirmation, in your setup are you able to get more than 1000 packets in the client RxPktCntr? In that case we will debug further and get back to you.

**Comment by rnhaddad** [comment]
Hi @rsindhujha,

Yes, here's a sample output for a queue side of 5000:
Packet Counters RxPktCntr(2800) RxPktCntrDrop(0) RxPktCntrQueued(2800)

**Comment by sharonshenzhen** [comment]
Hi @rnhaddad, Thanks for the update. 

What is the traffic rate? 

thanks,

Sharon

**Comment by rnhaddad** [comment]
The 2800 packets reported above was at 2pps for 1400 seconds.
However, the pps does not matter, we can test and report based on your traffic rate if you want. What is your traffic rate?

**Comment by sharonshenzhen** [comment]
@rnhaddad  
I use 200kbps for GDP packets and 100kbps for LLDP packets.  Packet size is 512.

**Comment by sharonshenzhen** [comment]
@rnhaddad 

We have find the root cause for this issue. 

Thank you for your support. Really appreciated. 

Best Regards, 

Sharon

**Comment by rnhaddad** [comment]
@sharonshenzhen Awesome! So it is a server issue i guess? Was suspecting that...

**Comment by sharonshenzhen** [comment]
@rnhaddad 
It is not the server issue.  It is the timing issue in the script. We need to add more delay after sending traffic.
